/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useMemo, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
export default function Model(props) {
  const ref = useRef();
  const { nodes, materials, animations } = useGLTF("/Portfolio-website/models/Meteo.glb");
  // const { actions, names } = useAnimations(animations, );
  const scroll = props.props;
  const viewport = useThree((state)=>state.viewport)
  useFrame((state,delta)=>{
    ref.current.rotation.z = ref.current.rotation.z+delta
    ref.current.rotation.x = 0
    ref.current.rotation.y = 0
  
  })
  let scale = useMemo(()=>{return Math.min(viewport.width,viewport.height) / 800*(1+scroll)}, [viewport, scroll])
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="obj_0"
          castShadow
          receiveShadow
          geometry={nodes.obj_0.geometry}
          material={materials.color_11909273}
          rotation={[Math.PI / 2, 0, 0]}
          scale={scale}
          position={[0, 0,-5]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Portfolio-website/models/Meteo.glb");
