/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../models/david.glb')
  const ref = useRef()
  useFrame((state,delta)=>{
    ref.current.rotation.z = 0
    ref.current.rotation.y = ref.current.rotation.y+delta
    ref.current.rotation.x = 0
  
  })
  return (

    <group ref={ref} {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['smk55-kas2232-head-of-david002'].geometry}
        material={nodes['smk55-kas2232-head-of-david002'].material}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('../models/david.glb')
